"""Tests for project-index-fetch and forecast-fetch commands."""

import json
import hashlib
from pathlib import Path
from unittest.mock import patch, MagicMock
from typer.testing import CliRunner

from manager_os.cli import app
from manager_os.ingest.project_sheet import validate_metadata


runner = CliRunner()


def test_project_index_fetch_writes_csv_and_metadata(tmp_path):
    """Test that project-index-fetch writes both CSV and metadata without errors."""
    local_csv = tmp_path / "project_index.csv"
    
    # Mock the Gemini CLI response
    mock_response = {
        "ok": True,
        "source": "google_sheet_project_index",
        "source_url": "https://docs.google.com/spreadsheets/d/test/edit?gid=123",
        "sheet_id": "test_sheet_id",
        "gid": "123",
        "retrieved_at": "2026-06-18T10:00:00Z",
        "rows": [
            ["Year", "Month", "Services ($)", "OppID", "Close Date", "Sales Rep", 
             "Customer", "Opp Name", "Services Delivery Team", "Solution Pillar", 
             "Type", "Industry", "3-5 words", "1-2 sentences"],
            ["2024", "6", "$100,000", "OPP001", "2024-06-15", "John Doe",
             "Acme Corp", "AI Platform", "AI/ML", "GenAI", "GenAI", "Technology",
             "AI platform", "Built AI platform for Acme Corp"]
        ]
    }
    
    with patch('subprocess.run') as mock_run:
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout=json.dumps(mock_response)
        )
        
        result = runner.invoke(app, [
            "project-index-fetch",
            "--force",
            "--output", str(local_csv),
            "--sheet-id", "test_sheet_id",
            "--gid", "123",
            "--sheet-url", "https://docs.google.com/spreadsheets/d/test/edit?gid=123"
        ])
        
        # Should succeed without "not readable" error
        assert result.exit_code == 0, f"Command failed: {result.output}"
        assert "not readable" not in result.output.lower()
        
        # CSV should exist
        assert local_csv.exists()
        
        # Metadata should exist
        meta_path = Path(f"{local_csv}.meta.json")
        assert meta_path.exists()
        
        # Metadata should have correct hash
        # Read in binary mode to get exact bytes (no line ending translation)
        with open(local_csv, "rb") as f:
            csv_bytes = f.read()
        
        expected_hash = hashlib.sha256(csv_bytes).hexdigest()
        
        with open(meta_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        
        assert metadata["content_hash"] == expected_hash
        assert metadata["row_count"] == 2  # header + 1 data row
        assert metadata["sheet_id"] == "test_sheet_id"
        assert metadata["gid"] == "123"


def test_project_index_metadata_validator_accepts_generated_metadata(tmp_path):
    """Test that validate_metadata accepts metadata generated by project-index-fetch."""
    local_csv = tmp_path / "project_index.csv"
    
    # Create a CSV file
    csv_content = "Year,Month,OppID\n2024,6,OPP001\n"
    with open(local_csv, "w", encoding="utf-8") as f:
        f.write(csv_content)
    
    # Create matching metadata
    content_hash = hashlib.sha256(csv_content.encode("utf-8")).hexdigest()
    meta_path = Path(f"{local_csv}.meta.json")
    metadata = {
        "source": "google_sheet_project_index",
        "sheet_id": "test_sheet_id",
        "gid": "123",
        "retrieved_at": "2026-06-18T10:00:00Z",
        "local_csv_path": str(local_csv),
        "row_count": 2,
        "content_hash": content_hash
    }
    
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f)
    
    # Validate metadata
    result = validate_metadata(str(local_csv), "test_sheet_id", "123", stale_hours=24)
    
    assert result.valid is True
    assert result.error == ""
    assert result.sheet_id == "test_sheet_id"
    assert result.gid == "123"


def test_index_projects_skip_fetch_succeeds_after_fetch(tmp_path):
    """Test that index-projects --skip-fetch succeeds after a successful fetch."""
    local_csv = tmp_path / "project_index.csv"
    
    # Create a valid CSV with proper headers (no leading whitespace)
    csv_content = "Year,Month,Services ($),OppID,Close Date,Sales Rep,Customer,Opp Name,Services Delivery Team,Solution Pillar,Type,Industry,3-5 words,1-2 sentences\n2024,6,$100000,OPP001,2024-06-15,John Doe,Acme Corp,AI Platform,AI/ML,GenAI,GenAI,Technology,AI platform,Built AI platform\n"
    with open(local_csv, "w", encoding="utf-8") as f:
        f.write(csv_content)
    
    # Create matching metadata
    content_hash = hashlib.sha256(csv_content.encode("utf-8")).hexdigest()
    meta_path = Path(f"{local_csv}.meta.json")
    metadata = {
        "source": "google_sheet_project_index",
        "sheet_id": "test_sheet_id",
        "gid": "123",
        "retrieved_at": "2026-06-18T10:00:00Z",
        "local_csv_path": str(local_csv),
        "row_count": 2,
        "content_hash": content_hash
    }
    
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f)
    
    # Run index-projects with --skip-fetch
    result = runner.invoke(app, [
        "index-projects",
        "--skip-fetch",
        "--force",
        "--verbose"
    ])
    
    # Should succeed
    assert result.exit_code == 0, f"Command failed: {result.output}"
    assert "Indexed" in result.output or "projects" in result.output.lower()


def test_forecast_fetch_writes_csv_and_metadata(tmp_path):
    """Test that forecast-fetch writes both CSV and metadata without errors."""
    local_csv = tmp_path / "forecast.csv"
    
    # Mock the Gemini CLI response
    mock_response = {
        "ok": True,
        "source": "google_sheet_forecast",
        "source_url": "https://docs.google.com/spreadsheets/d/test/edit?gid=456",
        "sheet_id": "test_forecast_sheet_id",
        "gid": "456",
        "retrieved_at": "2026-06-18T10:00:00Z",
        "rows": [
            ["Week", "Person", "Allocation"],
            ["2024-06-17", "Alice", "100%"]
        ]
    }
    
    with patch('subprocess.run') as mock_run:
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout=json.dumps(mock_response)
        )
        
        result = runner.invoke(app, [
            "forecast-fetch",
            "--force",
            "--output", str(local_csv),
            "--sheet-id", "test_forecast_sheet_id",
            "--gid", "456",
            "--sheet-url", "https://docs.google.com/spreadsheets/d/test/edit?gid=456"
        ])
        
        # Should succeed without "not readable" error
        assert result.exit_code == 0, f"Command failed: {result.output}"
        assert "not readable" not in result.output.lower()
        
        # CSV should exist
        assert local_csv.exists()
        
        # Metadata should exist
        meta_path = Path(f"{local_csv}.meta.json")
        assert meta_path.exists()
        
        # Metadata should have correct hash
        with open(local_csv, "r", encoding="utf-8") as f:
            csv_content = f.read()
        
        expected_hash = hashlib.sha256(csv_content.encode("utf-8")).hexdigest()
        
        with open(meta_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        
        assert metadata["content_hash"] == expected_hash
        assert metadata["row_count"] == 2  # header + 1 data row


def test_no_local_csv_fallback_introduced(tmp_path):
    """Test that no local CSV fallback behavior is introduced."""
    local_csv = tmp_path / "project_index.csv"
    
    # Create an old CSV with mismatched metadata
    csv_content = "Year,Month,OppID\n2024,6,OPP001\n"
    with open(local_csv, "w", encoding="utf-8") as f:
        f.write(csv_content)
    
    # Create metadata with wrong hash
    meta_path = Path(f"{local_csv}.meta.json")
    metadata = {
        "source": "google_sheet_project_index",
        "sheet_id": "test_sheet_id",
        "gid": "123",
        "retrieved_at": "2026-06-18T10:00:00Z",
        "local_csv_path": str(local_csv),
        "row_count": 2,
        "content_hash": "wrong_hash_that_doesnt_match"
    }
    
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f)
    
    # Run index-projects with --skip-fetch
    # Should fail because metadata hash doesn't match
    result = runner.invoke(app, [
        "index-projects",
        "--skip-fetch",
        "--force"
    ])
    
    # Should fail with metadata mismatch error, not silently use old CSV
    assert result.exit_code != 0
    assert "mismatch" in result.output.lower() or "metadata" in result.output.lower()
